export const GRID = 40;
export const HALF = GRID / 2; // pixel offset: tile center = gx * GRID + HALF
export const GRID_DIAG = GRID * Math.SQRT2; // ~56.57px for diagonal edges
export const ROAD_W = 30;
export const LANE_W = ROAD_W / 2;
export const CAR_LEN = 16;
export const CAR_WID = 10;
export const CAR_SPEED = 1.5;
export const CAR_ACCEL = 0.04; // acceleration per frame
export const CAR_DECEL = 0.06; // deceleration per frame (braking is faster)
export const CORNER_BRAKE_DIST = 30; // pixels from edge end to start braking for turns
export const CORNER_MIN_SPEED = 0.35; // minimum speed through a sharp (90°+) turn
export const CORNER_MED_SPEED = 0.8; // speed through a moderate (45°) turn
export const MIN_GAP = 10; // pixel gap between bumpers (rear of front car to front of behind car)
export const DASH_LEN = 10;
export const DASH_GAP = 8;
export const SPAWN_INTERVAL = 180; // frames (~3s at 60fps)
export const MAX_CARS_PER_HOUSE = 2;
export const PARK_DURATION = 120; // frames (~2s at 60fps)
export const PARK_ANIM_SPEED = 0.012; // progress per frame for parking/departing
export const TURN_LERP = 0.10; // angle interpolation speed per frame (0-1)
export const BG_COLOR = '#4a7c59';
export const ROAD_COLOR = '#555';
export const TOOLBAR_HEIGHT = 60;
export const PIN_SPAWN_INTERVAL = 900; // frames (~15s at 60fps)
export const PIN_COOLDOWN = 60; // frames (~1s at 60fps) before a new pin can be picked up
export const FACTORY_MAX_PINS = 6;
export const FACTORY_MAX_PARKED = 3;
export const NARROW_ROAD_W = 18;
export const STORAGE_W = 2;
export const STORAGE_H = 2;
export const STORAGE_MAX_PINS = 18;
export const STORAGE_MAX_PARKED = 1; // truck parking spot (1 truck per storage)
export const TRUCK_LEN = 22;
export const TRUCK_WID = 12;
export const TRUCK_SPEED = CAR_SPEED * 0.8;
export const TRUCK_CAPACITY = 6; // pins per truck load
export const MAX_TRUCKS_PER_STORAGE = 1;
export const TRUCK_SPAWN_INTERVAL = 300; // frames (~5s at 60fps)
export const HIGHWAY_SPEED = CAR_SPEED * 1.5;
export const HIGHWAY_COLOR = '#666';
export const HIGHWAY_ROAD_W = ROAD_W + 6;
